### ISSUE TITLE
How to train ?

### ISSUE THREAD

**Issue by zhongwenkun886** [Prasanna-icefire/Vehicle_Pedestrians_detector_droneClips#1]
hi , very great project !  
Can you explain how to train for the VisDrone dataset?

**Comment by Prasanna-icefire** [comment]
Hi there!
I have trained yolov4 on the visDrone Dataset itself.
After having downloaded the images and the annotations,you need to write a python script that will convert the given annotations into yolo format.
You need to first copy all the annotation files into the folder that contains its images.Copy the python file I am attaching with this, and execute it in the same folder as well. Having done this,the annotations are expected to be converted to yolo format,verify the same with the 'labelImg' command.
Having the dataset created successfully,follow the steps given here for training the custom dataset:
https://github.com/AlexeyAB/darknet#how-to-train-tiny-yolo-to-detect-your-custom-objects



I am uploading the python file for you here.


[annotations.py.zip](https://github.com/Prasanna-icefire/Vehicle_Pedestrians_detector_droneClips/files/4707217/annotations.py.zip)

**Comment by zhongwenkun886** [comment]
thanks very much !
